bountyfulcoins/urls.py
import os

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from bountyfulcoinsapp import views

site_media = os.path.join(
    os.path.dirname(__file__), 'site_media'
)

admin.autodiscover()

urlpatterns = patterns(
    '',

    # Browsing
    url(r'^$', views.HomePageView.as_view(), name='main_page'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^popular/$', views.PopularBountiesView.as_view(), name='popular'),

    # FIXME: Refactor points: CBV ME!
    url(r'^user/(\w+)/$', views.user_page, name='user_page'),
    url(r'^tag/([^\s]+)/$', views.tag_page, name='tag'),
    url(r'^tag/$', views.tag_cloud_page, name='tag_cloud'),

    # Session and user management
    url(r'^register/$', views.RegistrationView.as_view(),
        name='registration_register'),
    url(r'', include('registration.backends.default.urls')),
    url(r'^comments/', include('django_comments_xtd.urls')),

    # Content Management
    url(r'^bounty/$', views.BountyCreate.as_view(), name='create_bounty'),
    url(r'^bounty/(?P<pk>\d+)$', views.BountyChange.as_view(),
        name='change_bounty'),
    url(r'^bounty/(?P<pk>\d+)/details$', views.BountyDetails.as_view(),
        name='bounty_details'),
    url(r'^admin/bountyfulcoinsapp/address/import/$',
        views.ImportAddressView.as_view(filetype='csv'),
        name='import_address_csv'),
    url(r'^search/$', views.search_page, name='search'),
    url(r'^vote/$', views.bounty_vote_page),

    # Django Admin Page
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    # Site Media
    urlpatterns += url(
        r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': site_media}),

bountyfulcoinsapp/models.py
from collections import defaultdict
from datetime import timedelta
from itertools import groupby
from operator import itemgetter
import logging

from django.contrib.auth import get_user_model
from django.contrib.sites.models import Site
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from blockchain_adapter import blockchain

from utils import get_protocol, get_authenticated_twitter_api

logger = logging.getLogger('bountyfulcoinsapp.models')


class Link(models.Model):
    url = models.URLField(unique=True)

    def __unicode__(self):
        return self.url


class Bounty(models.Model):
    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'Bounties'

    link = models.ForeignKey(Link, verbose_name=_('Bounty URL'))
    title = models.CharField(_('Bounty Title'), max_length=200)
    user = models.ForeignKey(get_user_model())
    amount = models.DecimalField(_('Bounty Amount'), default=0.00,
                                 max_digits=20, decimal_places=8)
    currency = models.CharField(_('Bounty Currency'), default='BTC',
                                max_length=15)
    ctime = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return u'%s, %s' % (self.user.username, self.link.url)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('bounty_details', args=[str(self.id)])

    @property
    def full_url(self):
        return u"{protocol}{domain}{path}".format(
            protocol=get_protocol(getattr(self, '_request', None)),
            domain=Site.objects.get_current().domain.strip(' /'),
            path=self.get_absolute_url(),
        )

    def assign_tags_from_string(self, string):
        """
        Takes a list of string, by default sepererated by comma,
        and reassigns the tags to this bounty.
        """
        tag_names = string.split(',')
        self.tags.clear()  # remove existing tags before assigning new
        for tag_name in tag_names:
            tag, created = Tag.objects.get_or_create(name=tag_name.strip())
            self.tags.add(tag)

    @property
    def shared_date(self):
        try:
            return self.shared.last().date
        except SharedBounty.DoesNotExist:
            return None

    def share(self):
        """ Create a SharedBounty for this bounty """
        return SharedBounty.objects.get_or_create(bounty=self)

    def feature(self):
        """ Create a FeaturedBounty for this bounty """
        try:
            addr = Address.get_available_addresses().first()
        except Address.DoesNotExist:
            raise Exception('No assignable addresses found, '
                            'cannot feature bounty')
        self.featured = FeaturedBounty.objects.create(address=addr, bounty=self)
        return self.featured

    @property
    def is_featured(self):
        try:
            return bool(self.featured)
        except FeaturedBounty.DoesNotExist:
            return False

    def _get_tweet(self, request=None):
        self._request = request
        msg = (u"{b.ctime:%A} #bitcoin bounty paying {b.amount}"
               u" in #{b.currency} {b.full_url} #bountyful").format(b=self)
        if hasattr(self, '_request'):
            delattr(self, '_request')
        return msg

    def send_tweet(self, request=None):
        logger.debug('Entering send_tweet')
        tweeter_status = self._get_tweet(request)
        api = get_authenticated_twitter_api()
        api.update_status(tweeter_status)


class Tag(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=64, unique=True)
    bounties = models.ManyToManyField(Bounty, related_name='tags')

    def __unicode__(self):
        return self.name


class SharedBounty(models.Model):
    class Meta:
        ordering = ['-votes', '-date']
        verbose_name_plural = 'Shared bounties'

    bounty = models.ForeignKey(Bounty, unique=True, related_name='shared')
    date = models.DateTimeField(default=timezone.now)
    votes = models.IntegerField(default=1)
    users_voted = models.ManyToManyField(get_user_model())

    # if user decides to disable bounty later
    disabled = models.BooleanField(default=False)

    def __unicode__(self):
        return u'%s, %s' % (self.bounty, self.votes)


class Address(models.Model):
    name = models.CharField(max_length=255, blank=True)
    address_id = models.CharField(max_length=64, unique=True)

    verified_balance = models.DecimalField(default=0.00, max_digits=20,
                                           decimal_places=6)
    last_synced = models.DateTimeField(null=True, blank=True)

    @property
    def sync_required(self):
        if not settings.ADDRESSES_LIVE_SYNC:
            return False
        freq = timedelta(seconds=settings.ADDRESSES_SYNC_FREQUENCE)
        return (timezone.now() - self.last_synced) > freq

    def sync_verified_balance(self):
        """
        Using blockchain.info API get the latest balance of the Address.

        If a good result is returned, store it and update last_synced time.
        """
        res = blockchain.get_balance(self.address_id)
        if res is not None:
            self.verified_balance = res
            self.last_synced = timezone.now()
            self.save()
            return True
        return False

    @classmethod
    def get_available_addresses(cls):
        """
        Return assignable addresses, i.e: not related to a FeaturedBounty
        and have verified_balance of 0.00.
        """
        return cls.objects.filter(featured_bounty=None,
                                  verified_balance=0.00)

    @classmethod
    def bulk_create(cls, addr_list):
        """
        A helper method that inserts into the db the passed
        list of address dicts (excluding existing address ids).

        addr_list=[ {'name': 'abc', 'address_id': '1234'}, ... ]
        """
        # get and exclude dupes
        hashes = [a['address_id'] for a in addr_list]
        existing = cls.objects.filter(address_id__in=hashes).values_list(
            'address_id', flat=True)
        cls.objects.bulk_create([cls(**a) for a in addr_list
                                if a['address_id'] not in list(existing)])


class FeaturedBounty(models.Model):
    class Meta:
        ordering = ['-ctime']
        verbose_name_plural = 'Featured bounties'

    bounty = models.OneToOneField(Bounty, related_name='featured', null=True)
    address = models.OneToOneField(Address, unique=True,
                                   related_name='featured_bounty')
    ctime = models.DateTimeField(default=timezone.now)

    @property
    def enabled(self):
        if self.address.verified_balance >= settings.FEATURE_POST_MIN_CHARGE:
            return True
        elif self.address.last_synced is None or self.address.sync_required:
            res = self.address.sync_verified_balance()
            if res:  # balance was updated, check again
                return self.enabled
        # cannot verify payment was made, return False
        return False

    @classmethod
    def get_funded_entries(cls):
        return cls.objects.filter(
            address__verified_balance__gte=settings.FEATURE_POST_MIN_CHARGE)

    @property
    def target_address(self):
        """
        A wrapper property around the fwd address functionality falling
        back to using one of our available 0 addresses.
        """
        return self.address.address_id


def calculate_totals():
    bounties = sorted(
        list(SharedBounty.objects.values_list('bounty__currency',
                                              'bounty__amount')) +
        list(FeaturedBounty.get_funded_entries().values_list(
            'bounty__currency', 'bounty__amount')),
        key=itemgetter(0))
    totals = defaultdict(float)
    for currency, bounty_group in groupby(bounties, itemgetter(0)):
        totals[currency] += sum(float(b[1] or 0.0) for b in bounty_group)
    return dict(totals)

bountyfulcoins/templates/about.html
{% extends "base.html" %}

{% load staticfiles i18n %}

{% block title %}{% trans "About Bountyful Coins" %}{% endblock %}
{% block head_title %}{% trans "About Bountyful Coins" %}{% endblock head_title %}

{% block content %}
	<h2>{% trans "Who is Bountyful?" %}</h2>
	<p>{% blocktrans %}Bountyful Coins is an open-sourced Bounty listing application designed to organize and promote bounties on bitcoin and all other rising altocins. You will find all the possible jobs in crypto in this community.{% endblocktrans %}</p>
	<h2>{% trans "How to join the Bountyful Community" %}</h2>
	<p>Bountyful Coins <a href="https://github.com/bountyful/bountyfulcoins">{% trans "accepts pull requests" %}</a> {% trans "on Github to improve the platform functionality. You may also comment on bounties listed." %}</p>
	<h2>{% trans "How you can make money from this site" %}</h2>
	<p>{% trans "Click any Bounty listed that you like, deliver the work and get paid!" %}</p>
	<p>{% trans "Bountyful Coins generates revenue via featured and promoted Bounties. Revenue goes to pay Bounties of anyone (engineers, marketers, writers, BizDev) who want to help improve the platform to increase the flow of higher quality Bounties." %}</p>
	<p>{% trans "You will make even more money from Bountyfulcoins in three easy steps" %}:</p>
	<ul>
		<li>{% trans "Don't see a bount you like? Propose a task and Bounty amount or pick a task from our" %} <a href="https://www.pivotaltracker.com/s/projects/1025406" target="_new">Pivotal Tracker Icebox</a> </li>
		<li>{% trans "Complete the work and submit a pull request in our Github repo" %}</li>
		<li>{% trans "Test features and help us ensure quality of your submitted code or content and enjoy your bounty which will be paid in bitcoin (BTC)" %}</li>
	</ul>
{% endblock %}

bountyfulcoins/templates/base.html
{% load staticfiles bootstrap3 i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<title>{% trans "Bountyful Coins" %} | {% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static "/site_media/style.css" %}"
			type="text/css" />
	{% bootstrap_css %}
	<link rel="stylesheet" href="{% static "/site_media/bootstrap.min.css" %}"
</head>
<body>
	{% include "top_navigation.html" %}
	<div class="container">
		<div class="page-header">
			<div class="row">
				<div class="col-lg-6">
					{% block head %}
						{{ block.super }}
						<h1>{% block head_title %}{% endblock head_title %}</h1>
					{% endblock %}
				</div>
				
				<div class="col-lg-6">				
					{% block extra_head %}{% endblock %}
				</div>
			</div>
		</div>
		{% block content %}{% endblock %}
	</div>

	{# scripts go here to not block dom & css loading #}
	<script type="text/javascript" src="{% static "/site_media/jquery.js" %}"></script>
	{# <script type="text/javascript" src="{% static "/site_media/bitcoinaddress-bundle.js" %}"></script> #}
	<script type="text/javascript" src="{% static "/site_media/bitcoinaddress-bundle.min.js" %}"></script>
	{% block external %}{% endblock %}
	{% bootstrap_javascript %}
</body>
</html>

bountyfulcoins/templates/bitcoin_address_template.html
<div id="bitcoin-address-template" class="bitcoin-address-container" style="display: none">
    <div>
      <span class="bitcoin-address"></span>
    </div>
    <a href="#" class="bitcoin-address-action bitcoin-address-action-send">
      <i class="fa fa-btc"></i>
      Pay from wallet
    </a>
    <a href="#" class="bitcoin-address-action bitcoin-address-action-copy">
      <i class="fa fa-copy"></i>
      Copy
    </a>
    <a href="#" class="bitcoin-address-action bitcoin-address-action-qr">
      <i class="fa fa-qrcode"></i>
      QR code
    </a>
    <div class="bitcoin-action-hint bitcoin-action-hint-send">
      Sending payment to the address from locally installed Bitcoin wallet app.
    </div>
    <div class="bitcoin-action-hint bitcoin-action-hint-copy">
      Press CTRL + C or &#x2318; + C to copy the Bitcoin address.
    </div>
    <div class="bitcoin-action-hint bitcoin-action-hint-qr">
      <p>
        Scan the QR code with your mobile Bitcoin app to
        make the payment:
      </p>
      <div class="bitcoin-address-qr-container">
        <!-- Filled in by JS on action click -->
      </div>
    </div>
  </div>

  <script type="text/javascript" >
    $(document).ready(function() {
      bitcoinaddress.init({
        selector: ".bitcoin-address",
        template: "bitcoin-address-template",
        qr : {
          width: 128,
          height: 128,
          colorDark : "#000000",
          colorLight : "#ffffff"
        }
      });
    });
  </script>

bountyfulcoins/templates/bounty_details.html
{% extends "base.html" %}
{% load i18n comments comments_xtd %}

{% block title %}{% trans "Bounty" %} - {{object.title}}{% endblock title %}
{% block head_title %}{% trans "Bounty Details" %}{% endblock head_title %}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading"><h3>{{ object.title }}</h3></div>
  <div class="panel-body">
	<p>{% trans "Url" %}: <a href="{{ object.link }}">{{ object.link }}</a></p>
	<p>{% trans "Amount" %}: {{object.amount}} {{ object.currency }}</p>
	<p>{% trans "Keywords" %}: {{object.tags.all|join:", "|default:"None." }}</p>
	{% if object.is_featured %}
		<p>{% trans "This bounty is featured" %}</p>
	{% endif %}
	{% if object.shared_date %}
		<p>{% trans "Date posted" %}: {{ object.shared_date }}</p>
	{% endif %}
	{% if user == object.user %}
		{% trans "As the owner of this bounty, you may" %} <a href="{% url 'change_bounty' object.id %}">{% trans "edit it here" %}.</a>
	{% else %}
		<p>{% trans "Posted by" %}: {{ object.user }}</p>
	{% endif %}
	<hr>

	{% url 'bounty_details' object.id as bonty_url %}
	<div style="padding-bottom: 50px;">
		{% include "comments/form.html" with redirect_url=bonty_url %}
		{% render_comment_list for object %}
	</div>
  </div>
</div>

{% endblock %}

bountyfulcoins/templates/bounty_list.html
{% if bounties %}
	<ul class="bounties">
		{% for bounty in bounties %}
		<li>
			{{ bounty.amount }} {{ bounty.currency}}
			<a href="{{ bounty.link.url  }}" class="title">
				{{ bounty.title }}</a>
			<br />
			{% if show_edit %}
			<a href="{% url 'change_bounty' pk=bounty.pk %}"
				class="edit">[edit]</a>
			{% endif %}
			{% if show_tags %}
				Keywords:
				{% if bounty.tag_set.all %}
					<ul class="tags">
						{% for tag in bounty.tag_set.all %}
							<li>
								<a href="/tag/{{ tag.name }}/">{{ tag.name|urlencode }}</a>
							</li>
						{% endfor %}
					</ul>
				{% else %}
					None.
				{% endif %}
				<br />
			{% endif %}
			{% if show_user %}
				Bounty Posted by:
				<a href="/user/{{ bounty.user.username }}/"
					class="username">
					{{ bounty.user.username }}</a>
			{% endif %}
		</li>
		{% endfor %}
	</ul>
{% else %}
	<p> No bounties found.</p>
{% endif %}

bountyfulcoins/templates/bounty_save.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Post a Bounty" %}{% endblock %}
{% block head_title %}
	{% if object.pk %}
		{% trans "Edit Bounty" %}
	{% else %}
		{% trans "Post a Bounty" %}
	{% endif %}
{% endblock head_title %}


{% block content %}
	{% include "bounty_save_form.html" %}
{% endblock %}

{% block external %}
	{% include "bitcoin_address_template.html" %}
{% endblock external %}

bountyfulcoins/templates/bounty_save_form.html
{% load i18n bootstrap3 %}

<div class="row">
	<div class="col-lg-8 col-md-8">
		<div class="well">
			<form id="save-form" method="post" action="" class="form-horizontal" role="form">
				{% csrf_token %}
				<input type="hidden" name="next" value="/" />

				{% bootstrap_form form layout='horizontal' field_class='col-lg-10' label_class='col-lg-2' %}

				{% include "feature_payment.html" %}

				{% buttons %}
					<div class="col-lg-10 col-lg-offset-2">
						<button type="submit" class="btn btn-primary">
							{% trans "Save" %}
						</button>
						<input type="submit" name="_redirect" value="{% trans "Save & View" %}" class="btn btn-primary" />
					</div>
				{% endbuttons %}
			</form>
		</div>
	</div>
</div>

bountyfulcoins/templates/popular_page.html
{% extends "base.html" %}
{% block title %}Popular Bounties{% endblock %}
{% block head %}<h1>Most Popular Bounties</h1>{% endblock %}
{% block content %}
	{% include "featured_bounty_list.html" %}
	{% include "shared_bounty_list.html" %}
{% endblock %}

bountyfulcoins/templates/search.html
{% extends "base.html" %}
{% load i18n staticfiles bootstrap3 %}

{% block external %}
	<script type="text/javascript"
		src="{% static "/site_media/search.js" %}"></script>
{% endblock %}
{% block title %}{% trans "Search Bounties" %}{% endblock %}
{% block head_title %}{% trans "Search Bounties" %}{% endblock head_title %}
{% block content %}
<div class="well" style="max-width: 550px;">
	<form id="search-form" method="get" action=".">
	{% bootstrap_form form %}
	{% buttons %}
		<div>
			<button type="submit" class="btn btn-primary">
				{% trans "Search" %}
			</button>
		</div>
	{% endbuttons %}
</form>
</div>
<div id="search-results">
	{% if show_results %}
		{% include "bounty_list.html" %}
	{% endif %}
</div>
{% endblock %}

bountyfulcoins/templates/shared_bounty_list.html
<h2>Bitcoin and altcoin Bounties Posted</h2>
{% if shared_bounties %}
	{% include "homepage_bounty_list.html" with bounties=shared_bounties %}
{% else %}
	<p>No Shared Bounties Found.</p>
{% endif %}

bountyfulcoins/templates/tag_cloud_page.html
{% extends "base.html" %}
{% block title %}Keyword Tag Cloud{% endblock %}
{% block head %}Keyword Tag Cloud{% endblock %}
{% block content %}
	<div id="tag-cloud">
		{% for tag in tags %}
		<a href="/tag/{{ tag.name|urlencode }}/"
		class="tag-cloud-{{ tag.weight }}">
		{{ tag.name }}</a>
		{% endfor %}
	</div>
{% endblock %}

bountyfulcoins/templates/top_navigation.html
{% load i18n %}

<div class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'main_page' %}">{% trans "Bountyful Coins" %}</a>
		</div>
		<div class="navbar-collapse navbar-responsive-collapse collapse" style="height: 1px;">
			{# TODO: add active class to the currently active page #}
			<ul class="nav navbar-nav">
				<li><a href="{% url 'popular' %}">{% trans "Popular" %}</a></li>
				<li><a href="{% url 'about' %}">{% trans "About" %}</a></li>
				{% if user.is_authenticated %}
					<li><a href="{% url 'create_bounty' %}">{% trans "Submit" %}</a></li>
				{% endif %}
			</ul>

			<form method="get" action="{% url 'search' %}" class="navbar-form navbar-left">
				<input type="text" class="form-control col-lg-8 col-md-4" name="query" placeholder="Search" value="{{ request.GET.query }}">
			</form>

			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
					<li><a href="{% url 'user_page' user.username %}">{{ user.username }}</a></li>
					<li><a href="{% url 'auth_logout' %}">{% trans "Logout" %}</a></li>
				{% else %}
					<li><a href="{% url 'auth_login' %}">{% trans "Login" %}</a></li> 
					<li><a href="{% url 'registration_register' %}">{% trans "Register" %}</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</div>

bountyfulcoins/templates/total_bounties.html
<h2>Total Bounties Posted</h2>
{% if total_bounties %}
	<ul>
		{% for currency, amount in total_bounties.items %}
			<li>{{amount}} {{currency}}</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No bounties posted yet!</p>
{% endif %}

bountyfulcoins/templates/user_page.html
{% extends "base.html" %}
{% load i18n staticfiles %}

{% block external %}
	<script type="text/javascript"
		src="{% static "/site_media/bounty_edit.js" %}"></script>
	{% endblock %}
{% block title %}{{ username }}{% endblock %}
{% block head_title %}{% trans "Bounties by" %} {{ username }} {% endblock head_title %}
{% block content %}
	{% include "bounty_list.html" %}
{% endblock %}